### ISSUE TITLE
"Command Not Found" in macOS 12+

### ISSUE THREAD

**Issue by umesh-bhat-inbank** [kdheepak/d2-markdown-preview#1]
**Operating System**: MacOS Monterey (12.6.4), Apple Silicon M2
**Visual Studio Code**: 1.77.3 (Universal) Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
**VSCode Extension**: v0.0.8

*Steps to Reproduce*:
- Install the [d2-markdown-preview](https://marketplace.visualstudio.com/items?itemName=kdheepak.d2-markdown-preview) extension.
- Write a simple D2 diagram in a markdown file.
- Switch to Markdown preview in VS Code.
- Observe the crash message `/bin/sh: d2: command not found`.
![Screenshot 2023-04-14 at 16 48 18](https://user-images.githubusercontent.com/110083993/232064081-d9160062-1368-4aca-a8ba-3a43d1f43a0c.png)

**Comment by kdheepak** [comment]
Have you installed `d2`?

**Comment by umesh-bhat-inbank** [comment]
1. Installed `d2`, issue fixed.
2. However, the VSCode Extension documentation needs to mention that `d2` needs to be installed.

Thanks, @kdheepak.
